### PR TITLE
update the final model and deployed app

### PR DESCRIPTION
**Pull request by shemaaali**
Update the final model and deployed the app

### CODE REVIEW

**Review by shemaaali — COMMENTED** [review]
Update final model and deployed app

**Review by mattdmeans — APPROVED** [review]

**Comment by shemaaali** [comment]
Update the final model and deployed app through heroku

**Comment by shemaaali** [comment]
Update the final model and deployed app through heroku

**Review by shemaaali — COMMENTED** [review]
Update the final model

**Comment by shemaaali** [comment]
The final model has been updated

**Comment by shemaaali** [comment]
Update the final model and deployed app through heroku

**Pull request merged**
